spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user-profile
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
springdoc:
  show-actuator: true
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: liquibase, health
server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:security/user_profile_keystore_dev.p12
    key-store-password: securepass
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    trust-store: classpath:security/user_profile_truststore_dev.p12
    trust-store-password: securepass

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changeset/test-data-e2e/db.changelog-master-test.yaml
management:
  endpoints:
    web:
      exposure:
        include: liquibase, health, mappings