version: '3.9'

volumes:
  db-data:
    driver: local

services:
  product-service:
    image: user-profile-service
    build:
      dockerfile: Dockerfile
    container_name: user-profile
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres

  postgres:
    container_name: postgres-container
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
