version: '3.9'

volumes:
  db-data-user-profile-service-e2e:
    driver: local

services:
  user-profile-service:
    image: user-profile-service
    container_name: user-profile-service
    build:
      context: ../
      dockerfile: ../app/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-e2e:5432/${POSTGRES_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres-e2e
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - db-data-user-profile-service-e2e:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:8.5.21
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - influxdb
      - prometheus

  k6:
    image: grafana/k6:0.48.0
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../performance_scripts:/scripts
    depends_on:
      - influxdb

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: monitoring-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"

  promtail:
    image: grafana/promtail:main
    container_name: monitoring-promtail
    volumes:
      - ./promtail/promtail-docker-config.yaml:/etc/promtail/docker-config.yaml
      - ../logs/:/var/log/

    command: "--config.file=/etc/promtail/docker-config.yaml"
  loki:
    image: grafana/loki:main
    container_name: monitoring-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
